script: bundle exec rake test

rvm:
  - 2.1

notifications:
  email:
    recipients:
      - monitoring@respoke.io
    email:
      on_success: change
      on_failure: always

cache: bundler

os:
  - linux
  - osx
